### Registrasi success
POST http://0.0.0.0:3000/api/user/registrasi
Accept: application/json
Content-Type: application/json

{
    "email": "aku@mail.com",
    "username": "andini",
    "password": "Atlanti322k"
}

### Registrasi validation failed (Bad request)
POST http://0.0.0.0:3000/api/user/registrasi
Accept: application/json
Content-Type: application/json

{
    "email": "aku@mail.com",
    "username": "andini",
    "password": "Atlantik"
}

### Login success
POST http://localhost:3000/api/user/login
Accept: application/json
Content-Type: application/json

{
    "username": "andini",
    "password": "Atlanti322k"
}

### Login validation failed (Not found)
POST http://localhost:3000/api/user/login
Accept: application/json
Content-Type: application/json

{
    "username": "jameLili",
    "password": "Atlanti322k"
}

### add new todo
POST http://0.0.0.0:3000/api/todo
Accept: application/json
Content-Type: application/json
authorization: v2.local.7rYnAF5wkeBEGo4RaJB62kWxm-MWzgHKrwUaQXnXd5QADcCHf8eskbyA2qoZJSHAc2l6X9KXSuc0mTz2wFEemgQXx9t-wSJX-y4zhQM7dZg4DSa7PUeerfy8OQ4NqBMiPAE-wD4ZRSk0Sb5HNRl1s3oFke7I8T3vPRgvPdf9p4u5Iaafukik6lgMSFGZ5EuhD0dJk4AvXS2236GUoLRZzO_VuXuKlP17wJ2OSKJPxgPyOgF4W3O9LsQgBiZJxcIZa7t9yBiWVud_CzQkSHQEFZK_vfifi7UTVQ.bnVsbA

{
    "todo": "pray to god in night",
    "complated": false,
    "userid": 1
}


### Get All todo
GET http://localhost:3000/api/todos/1
Accept: application/json
authorization: v2.local.GDt-7ZGe78rCroGhXN3Tkk_cRdHmBWrKulPY4L8sYX3TAzSton1RFQ428y7M_wW-wLIWbgjXDBXjOhVR0v5eBEL6i8Vkfs7L8UwA_HpxSOSDBGDlrFa0wmtbcDfuTAFZkXkZfpLwe1djdHN8wFJUOcsB0uKZYJSq0VbmH1P85eVlHtvpbJW3bv_E0pY0P5gq9JeWrX4Q52kAWzATyPARS5b5USWTQyP64ECVy-BktpS_Y7CWo4Li8vqi11FSuocBUGCpDCpsGOl1Ueju_znXI_UZJE5DZH_kEOWIzbo.bnVsbA

### Get random todo
GET http://localhost:3000/api/todo/random/54
Accept: application/json
authorization: v2.local.hgR2n61ejzQ1e-_1bT8L-XM_tENC_z2rIhwrkTQ36bMrU5ePNy0SExLpznnAji2nANFy-8ncLfyLJIVQ3C5EwUEn8wnwBr31iLVYaDwX64kQoVxkM6xguTZMH6IHL484kV8Y1h6fzNOBZDDNFydH7tqUJY2WUV6W6OmSNWZzUw3PSZWBibQJ02i_8D42m6kGpA-NDUlsiKt365ImG5bpNRtdG4RwEECmppYwqDZj9ZzlTZ8dIiKdAROQ6tcGaYT5kkQkybKtvLsVbYFXjl8.bnVsbA

### Get a todo
GET http://localhost:3000/api/todo?userId=54&id=367
Accept: application/json
authorization: v2.local.hgR2n61ejzQ1e-_1bT8L-XM_tENC_z2rIhwrkTQ36bMrU5ePNy0SExLpznnAji2nANFy-8ncLfyLJIVQ3C5EwUEn8wnwBr31iLVYaDwX64kQoVxkM6xguTZMH6IHL484kV8Y1h6fzNOBZDDNFydH7tqUJY2WUV6W6OmSNWZzUw3PSZWBibQJ02i_8D42m6kGpA-NDUlsiKt365ImG5bpNRtdG4RwEECmppYwqDZj9ZzlTZ8dIiKdAROQ6tcGaYT5kkQkybKtvLsVbYFXjl8.bnVsbA

### Update status todo
PUT http://localhost:3000/api/todo?userId=54&id=367 
Accept: application/json
Content-Type: application/json
authorization: v2.local.hgR2n61ejzQ1e-_1bT8L-XM_tENC_z2rIhwrkTQ36bMrU5ePNy0SExLpznnAji2nANFy-8ncLfyLJIVQ3C5EwUEn8wnwBr31iLVYaDwX64kQoVxkM6xguTZMH6IHL484kV8Y1h6fzNOBZDDNFydH7tqUJY2WUV6W6OmSNWZzUw3PSZWBibQJ02i_8D42m6kGpA-NDUlsiKt365ImG5bpNRtdG4RwEECmppYwqDZj9ZzlTZ8dIiKdAROQ6tcGaYT5kkQkybKtvLsVbYFXjl8.bnVsbA

{
    "complated": false
}

### Delete todo
DELETE http://localhost:3000/api/todo?userId=54&id=369
Accept: application/json
authorization: v2.local.hgR2n61ejzQ1e-_1bT8L-XM_tENC_z2rIhwrkTQ36bMrU5ePNy0SExLpznnAji2nANFy-8ncLfyLJIVQ3C5EwUEn8wnwBr31iLVYaDwX64kQoVxkM6xguTZMH6IHL484kV8Y1h6fzNOBZDDNFydH7tqUJY2WUV6W6OmSNWZzUw3PSZWBibQJ02i_8D42m6kGpA-NDUlsiKt365ImG5bpNRtdG4RwEECmppYwqDZj9ZzlTZ8dIiKdAROQ6tcGaYT5kkQkybKtvLsVbYFXjl8.bnVsbA

### Get todos with filter
GET http://localhost:3000/api/todos?userId=54&limit=2&offset=2
Accept: application/json
authorization: v2.local.hgR2n61ejzQ1e-_1bT8L-XM_tENC_z2rIhwrkTQ36bMrU5ePNy0SExLpznnAji2nANFy-8ncLfyLJIVQ3C5EwUEn8wnwBr31iLVYaDwX64kQoVxkM6xguTZMH6IHL484kV8Y1h6fzNOBZDDNFydH7tqUJY2WUV6W6OmSNWZzUw3PSZWBibQJ02i_8D42m6kGpA-NDUlsiKt365ImG5bpNRtdG4RwEECmppYwqDZj9ZzlTZ8dIiKdAROQ6tcGaYT5kkQkybKtvLsVbYFXjl8.bnVsbA
