// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package repository

import (
	"database/sql"
)

type Todo struct {
	ID        int32        `json:"id"`
	Todo      string       `json:"todo"`
	Complated bool         `json:"complated"`
	Userid    int32        `json:"userid"`
	Isdelete  bool         `json:"isdelete"`
	Deletedon sql.NullTime `json:"deletedon"`
}

type User struct {
	Userid   int32  `json:"userid"`
	Email    string `json:"email"`
	Username string `json:"username"`
	Password string `json:"password"`
}
