// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package repository

import (
	"context"
)

type Querier interface {
	AddaNewTodo(ctx context.Context, arg AddaNewTodoParams) (Todo, error)
	CountAllTodos(ctx context.Context, userid int32) (int64, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (User, error)
	DeleteaTodo(ctx context.Context, arg DeleteaTodoParams) (Todo, error)
	GetAccount(ctx context.Context, userid int32) (User, error)
	GetAllTodos(ctx context.Context, userid int32) ([]Todo, error)
	GetRandomaTodo(ctx context.Context) (Todo, error)
	GetSingleaTodos(ctx context.Context, arg GetSingleaTodosParams) (Todo, error)
	GetSomeTodos(ctx context.Context, arg GetSomeTodosParams) ([]Todo, error)
	UpdateStatusComplate(ctx context.Context, arg UpdateStatusComplateParams) (Todo, error)
}

var _ Querier = (*Queries)(nil)
